version: 2
updates:
  - package-ecosystem: "nuget"
    target-branch: "main"
    directory: "UI/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
