name: Build UI

on:
  push:
    branches: [ "main" ]
    paths:
      - UI/**
  pull_request:
    paths:
      - UI/**
  workflow_dispatch:


defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Release
        target-platform:
          - { os: ubuntu-latest, name: linux }
          - { os: windows-latest, name: win }
          - { os: macos-latest, name: osx }
        target-arch:
          - x64
          - arm64
        dotnet-version:
          - "8.0"
        self-contained:
          - true

    runs-on: ${{ matrix.target-platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build Project
        run: |
          dotnet publish UI/PBL3.sln --configuration=${{ matrix.build-type }} --arch=${{ matrix.target-arch }} --self-contained=${{ matrix.self-contained }}

      - name: List Result
        working-directory: ./
        run: |
          ls -l UI/bin/${{ matrix.build-type }}/net${{ matrix.dotnet-version }}/${{matrix.target-platform.name}}-${{ matrix.target-arch }}/publish

      - name: Package Build
        working-directory: ./
        run: |
          7z a -tzip PBL3.zip ./UI/bin/${{ matrix.build-type }}/net${{ matrix.dotnet-version }}/${{matrix.target-platform.name}}-${{ matrix.target-arch }}/publish/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PBL3-${{ matrix.target-platform.name }}-${{ matrix.target-arch }}
          path: PBL3.zip