name: Build UI

on:
  push:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Release
        target-platform:
          - {os = ubuntu-latest, name = linux}
          - {os = windows-latest, name = win}
          - {os = osx-latest, name = osx}
        target-arch:
          - x64
          - arm64
        dotnet-version:
          - "8.0"
        self-contained:
          - true

    runs-on: ${{ matrix.target-platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build Project
        run: |
          cd UI
          dotnet publish --configuration=${{ matrix.build-type }} --arch=${{ matrix.target-arch }} --self-contained=${{ matrix.self-contained }}

      - name: List result
        run: |
            ls -l UI/bin/${{ matrix.build-type }}/net${{ matrix.dotnet-version }}/${{matrix.target-platform.name}}-${{ matrix.target-arch }}/publish
        shell: bash
